//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        internal static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear *Name*,&lt;br/&gt; Your reservation in *RestName* have been cancelled..
        /// </summary>
        internal static string CancelledResContent {
            get {
                return ResourceManager.GetString("CancelledResContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Cancelled.
        /// </summary>
        internal static string CancelledResSubject {
            get {
                return ResourceManager.GetString("CancelledResSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        internal static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Residence.
        /// </summary>
        internal static string Countryofresidence {
            get {
                return ResourceManager.GetString("Countryofresidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DayText {
            get {
                return ResourceManager.GetString("DayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily unable to process your request. Please try after some time..
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name.
        /// </summary>
        internal static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;br/&gt;Regards,&lt;br/&gt;eat2eat Pte Ltd&lt;br/&gt;&lt;a href=&quot;http://www.eat2eat.com&quot;&gt;www.eat2eat.com&lt;/a&gt;.
        /// </summary>
        internal static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Hotel Brand --.
        /// </summary>
        internal static string FrontBrand {
            get {
                return ResourceManager.GetString("FrontBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select City --.
        /// </summary>
        internal static string FrontCity {
            get {
                return ResourceManager.GetString("FrontCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Restaurant, Bar + Spa --.
        /// </summary>
        internal static string FrontConcept {
            get {
                return ResourceManager.GetString("FrontConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Hotel --.
        /// </summary>
        internal static string FrontHotel {
            get {
                return ResourceManager.GetString("FrontHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours:.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Diner(s).
        /// </summary>
        internal static string NumberofDiners {
            get {
                return ResourceManager.GetString("NumberofDiners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Room(s).
        /// </summary>
        internal static string NumberOfRooms {
            get {
                return ResourceManager.GetString("NumberOfRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer valid from: .
        /// </summary>
        internal static string OfferValid {
            get {
                return ResourceManager.GetString("OfferValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Reservation Details.
        /// </summary>
        internal static string OldReservationDetails {
            get {
                return ResourceManager.GetString("OldReservationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Number: .
        /// </summary>
        internal static string PageNumber {
            get {
                return ResourceManager.GetString("PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        internal static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Copyright 2011 eat2eat Pte. Ltd. | All rights reserved..
        /// </summary>
        internal static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        internal static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Details.
        /// </summary>
        internal static string ReservationDetails {
            get {
                return ResourceManager.GetString("ReservationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        internal static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :: Select ::.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Country--.
        /// </summary>
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Diners : .
        /// </summary>
        internal static string TotalDiners {
            get {
                return ResourceManager.GetString("TotalDiners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hits : .
        /// </summary>
        internal static string TotalHits {
            get {
                return ResourceManager.GetString("TotalHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total record(s) : .
        /// </summary>
        internal static string TotalNumber {
            get {
                return ResourceManager.GetString("TotalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot; charset=&quot;utf-8&quot;&gt;
        ///        function eat2eatWidgetLoader(result) {
        ///            if (result.length == 0) {
        ///                $(&apos;#no_eat2eat&apos;).show();
        ///                $(&apos;#eat2eat_widget&apos;).hide();
        ///            } else {
        ///                $(&apos;#eat2eat_widget&apos;).html(result);
        ///                LoadDatesInList();
        ///            }
        ///        }
        ///    &lt;/script&gt;
        ///&lt;div id=&quot;eat2eat_widget&quot;&gt;
        ///&lt;/div&gt;
        ///&lt;div id=&quot;no_eat2eat&quot; style=&quot;display:none;&quot; class=&quot;warning&quot;&gt;Kindly contact to administrator.&lt;/div&gt;
        ///&lt;sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebWidgetScript {
            get {
                return ResourceManager.GetString("WebWidgetScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot; charset=&quot;utf-8&quot;&gt;
        ///        function eat2eatWidgetLoader(result) {
        ///            if (result.length == 0) {
        ///                $(&apos;#no_eat2eat&apos;).show();
        ///                $(&apos;#eat2eat_widget&apos;).hide();
        ///            } else {
        ///                $(&apos;#eat2eat_widget&apos;).html(result);
        ///                LoadDatesInList();
        ///            }
        ///        }
        ///    &lt;/script&gt;
        ///&lt;div id=&quot;eat2eat_widget&quot;&gt;
        ///&lt;/div&gt;
        ///&lt;div id=&quot;no_eat2eat&quot; style=&quot;display:none;&quot; class=&quot;warning&quot;&gt;Kindly contact to administrator.&lt;/div&gt;
        ///&lt;sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WidgetScript {
            get {
                return ResourceManager.GetString("WidgetScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string YearText {
            get {
                return ResourceManager.GetString("YearText", resourceCulture);
            }
        }
    }
}
